// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/nochaosio/opentelemetry-collector-gateway/processor/ratelimitprocessor/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	require.NoError(t, tb.RegisterProcessorRatelimitBucketAvailableTokensCallback(func(_ context.Context, observer metric.Float64Observer) error {
		observer.Observe(1)
		return nil
	}))
	require.NoError(t, tb.RegisterProcessorRatelimitBucketCapacityTokensCallback(func(_ context.Context, observer metric.Float64Observer) error {
		observer.Observe(1)
		return nil
	}))
	tb.ProcessorRatelimitAllowedItems.Add(context.Background(), 1)
	tb.ProcessorRatelimitBackendErrors.Add(context.Background(), 1)
	tb.ProcessorRatelimitBucketEvictions.Add(context.Background(), 1)
	tb.ProcessorRatelimitDeniedItems.Add(context.Background(), 1)
	tb.ProcessorRatelimitFailOpenItems.Add(context.Background(), 1)
	tb.ProcessorRatelimitPreservedItems.Add(context.Background(), 1)
	tb.ProcessorRatelimitReceivedItems.Add(context.Background(), 1)
	AssertEqualProcessorRatelimitAllowedItems(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitBackendErrors(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitBucketAvailableTokens(t, testTel,
		[]metricdata.DataPoint[float64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitBucketCapacityTokens(t, testTel,
		[]metricdata.DataPoint[float64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitBucketEvictions(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitDeniedItems(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitFailOpenItems(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitPreservedItems(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorRatelimitReceivedItems(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
