// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/nochaosio/opentelemetry-collector-gateway/processor/ratelimitprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/nochaosio/opentelemetry-collector-gateway/processor/ratelimitprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                   metric.Meter
	mu                                      sync.Mutex
	registrations                           []metric.Registration
	ProcessorRatelimitAllowedItems          metric.Int64Counter
	ProcessorRatelimitBackendErrors         metric.Int64Counter
	ProcessorRatelimitBucketAvailableTokens metric.Float64ObservableGauge
	ProcessorRatelimitBucketCapacityTokens  metric.Float64ObservableGauge
	ProcessorRatelimitBucketEvictions       metric.Int64Counter
	ProcessorRatelimitDeniedItems           metric.Int64Counter
	ProcessorRatelimitFailOpenItems         metric.Int64Counter
	ProcessorRatelimitPreservedItems        metric.Int64Counter
	ProcessorRatelimitReceivedItems         metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterProcessorRatelimitBucketAvailableTokensCallback sets callback for observable ProcessorRatelimitBucketAvailableTokens metric.
func (builder *TelemetryBuilder) RegisterProcessorRatelimitBucketAvailableTokensCallback(cb metric.Float64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerFloat64{inst: builder.ProcessorRatelimitBucketAvailableTokens, obs: o})
		return nil
	}, builder.ProcessorRatelimitBucketAvailableTokens)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRatelimitBucketCapacityTokensCallback sets callback for observable ProcessorRatelimitBucketCapacityTokens metric.
func (builder *TelemetryBuilder) RegisterProcessorRatelimitBucketCapacityTokensCallback(cb metric.Float64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerFloat64{inst: builder.ProcessorRatelimitBucketCapacityTokens, obs: o})
		return nil
	}, builder.ProcessorRatelimitBucketCapacityTokens)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerFloat64 struct {
	embedded.Float64Observer
	inst metric.Float64Observable
	obs  metric.Observer
}

func (oi *observerFloat64) Observe(value float64, opts ...metric.ObserveOption) {
	oi.obs.ObserveFloat64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorRatelimitAllowedItems, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_allowed_items",
		metric.WithDescription("Number of items allowed through by the rate limit processor [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitBackendErrors, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_backend_errors",
		metric.WithDescription("Transient errors from the rate-limit storage backend (e.g. Redis unreachable while fail-open) [Alpha]"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitBucketAvailableTokens, err = builder.meter.Float64ObservableGauge(
		"otelcol_processor_ratelimit_bucket_available_tokens",
		metric.WithDescription("Token-bucket tokens currently available (free) for watched keys; occupied = capacity - available [Alpha]"),
		metric.WithUnit("{token}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitBucketCapacityTokens, err = builder.meter.Float64ObservableGauge(
		"otelcol_processor_ratelimit_bucket_capacity_tokens",
		metric.WithDescription("Token-bucket capacity (max tokens == configured limit) for watched keys [Alpha]"),
		metric.WithUnit("{token}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitBucketEvictions, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_bucket_evictions",
		metric.WithDescription("Buckets evicted because the memory backend hit its max_buckets cap [Alpha]"),
		metric.WithUnit("{bucket}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitDeniedItems, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_denied_items",
		metric.WithDescription("Number of items denied by the rate limit processor [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitFailOpenItems, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_fail_open_items",
		metric.WithDescription("Items allowed through because the storage backend was unreachable (fail-open) and thus NOT rate-limited [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitPreservedItems, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_preserved_items",
		metric.WithDescription("Number of critical items preserved via priority bypass (error spans, error+ logs) [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRatelimitReceivedItems, err = builder.meter.Int64Counter(
		"otelcol_processor_ratelimit_received_items",
		metric.WithDescription("Number of items received by the rate limit processor [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
