// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/nochaosio/opentelemetry-collector-gateway/processor/statefulfilterprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/nochaosio/opentelemetry-collector-gateway/processor/statefulfilterprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                  metric.Meter
	mu                                     sync.Mutex
	registrations                          []metric.Registration
	ProcessorStatefulfilterDroppedItems    metric.Int64Counter
	ProcessorStatefulfilterEvaluatedItems  metric.Int64Counter
	ProcessorStatefulfilterKeptItems       metric.Int64Counter
	ProcessorStatefulfilterRefreshErrors   metric.Int64ObservableGauge
	ProcessorStatefulfilterRulesAgeSeconds metric.Float64ObservableGauge
	ProcessorStatefulfilterRulesInvalid    metric.Int64ObservableGauge
	ProcessorStatefulfilterRulesLoaded     metric.Int64ObservableGauge
	ProcessorStatefulfilterRulesVersion    metric.Int64ObservableGauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterProcessorStatefulfilterRefreshErrorsCallback sets callback for observable ProcessorStatefulfilterRefreshErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorStatefulfilterRefreshErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorStatefulfilterRefreshErrors, obs: o})
		return nil
	}, builder.ProcessorStatefulfilterRefreshErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorStatefulfilterRulesAgeSecondsCallback sets callback for observable ProcessorStatefulfilterRulesAgeSeconds metric.
func (builder *TelemetryBuilder) RegisterProcessorStatefulfilterRulesAgeSecondsCallback(cb metric.Float64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerFloat64{inst: builder.ProcessorStatefulfilterRulesAgeSeconds, obs: o})
		return nil
	}, builder.ProcessorStatefulfilterRulesAgeSeconds)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorStatefulfilterRulesInvalidCallback sets callback for observable ProcessorStatefulfilterRulesInvalid metric.
func (builder *TelemetryBuilder) RegisterProcessorStatefulfilterRulesInvalidCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorStatefulfilterRulesInvalid, obs: o})
		return nil
	}, builder.ProcessorStatefulfilterRulesInvalid)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorStatefulfilterRulesLoadedCallback sets callback for observable ProcessorStatefulfilterRulesLoaded metric.
func (builder *TelemetryBuilder) RegisterProcessorStatefulfilterRulesLoadedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorStatefulfilterRulesLoaded, obs: o})
		return nil
	}, builder.ProcessorStatefulfilterRulesLoaded)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorStatefulfilterRulesVersionCallback sets callback for observable ProcessorStatefulfilterRulesVersion metric.
func (builder *TelemetryBuilder) RegisterProcessorStatefulfilterRulesVersionCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorStatefulfilterRulesVersion, obs: o})
		return nil
	}, builder.ProcessorStatefulfilterRulesVersion)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

type observerFloat64 struct {
	embedded.Float64Observer
	inst metric.Float64Observable
	obs  metric.Observer
}

func (oi *observerFloat64) Observe(value float64, opts ...metric.ObserveOption) {
	oi.obs.ObserveFloat64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorStatefulfilterDroppedItems, err = builder.meter.Int64Counter(
		"otelcol_processor_statefulfilter_dropped_items",
		metric.WithDescription("Items dropped by a shared filter rule, labelled by the rule that matched [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterEvaluatedItems, err = builder.meter.Int64Counter(
		"otelcol_processor_statefulfilter_evaluated_items",
		metric.WithDescription("Items (spans, log records, metric data points) evaluated against the Redis rule set [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterKeptItems, err = builder.meter.Int64Counter(
		"otelcol_processor_statefulfilter_kept_items",
		metric.WithDescription("Items explicitly rescued by a keep rule that would otherwise have matched a drop rule [Alpha]"),
		metric.WithUnit("{item}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterRefreshErrors, err = builder.meter.Int64ObservableGauge(
		"otelcol_processor_statefulfilter_refresh_errors",
		metric.WithDescription("Total failed rule refreshes since start (Redis unreachable, timeout); rules go stale, not empty [Alpha]"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterRulesAgeSeconds, err = builder.meter.Float64ObservableGauge(
		"otelcol_processor_statefulfilter_rules_age_seconds",
		metric.WithDescription("Seconds since the last successful rule refresh; climbing means this replica is enforcing stale rules [Alpha]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterRulesInvalid, err = builder.meter.Int64ObservableGauge(
		"otelcol_processor_statefulfilter_rules_invalid",
		metric.WithDescription("Rule documents rejected at the last refresh (bad JSON, unknown operator, bad regex) [Alpha]"),
		metric.WithUnit("{rule}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterRulesLoaded, err = builder.meter.Int64ObservableGauge(
		"otelcol_processor_statefulfilter_rules_loaded",
		metric.WithDescription("Filter rules currently active on this replica [Alpha]"),
		metric.WithUnit("{rule}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorStatefulfilterRulesVersion, err = builder.meter.Int64ObservableGauge(
		"otelcol_processor_statefulfilter_rules_version",
		metric.WithDescription("Rule-set version this replica has applied; diverging values across replicas mean the fleet is out of sync [Alpha]"),
		metric.WithUnit("{version}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
