receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317

processors:
  ratelimit:
    limit_type: service_name
    requests_per_second: 1000
    drop_on_limit: true

exporters:
  debug:
    verbosity: basic

service:
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 18888
    logs:
      level: error
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ratelimit]
      exporters: [debug]
